spring.application.name=backend


# PostgreSQL
spring.datasource.url={___}
spring.datasource.username={___}
spring.datasource.password={___}
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA
spring.jpa.hibernate.ddl-auto=update

spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# JWT
jwt.secret=mySuperSecretKeyForJWTGenerationWithAtLeast32BytesLong!
jwt.expiration=86400000

# Logging
logging.level.org.springframework.security=DEBUG