CREATE TABLE IF NOT EXISTS users (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    login VARCHAR(100) UNIQUE NOT NULL,
    password VARCHAR(200) NOT NULL,
    name VARCHAR(200),
    interests_selected BOOLEAN NOT NULL DEFAULT FALSE,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS interests (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(100) NOT NULL
);

CREATE TABLE IF NOT EXISTS user_interests (
    user_id BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    interest_id BIGINT NOT NULL REFERENCES interests(id),
    PRIMARY KEY(user_id, interest_id)
);

CREATE TABLE IF NOT EXISTS challenges (
    id BIGINT PRIMARY KEY,
    title VARCHAR(255) NOT NULL,
    image VARCHAR(255),
    description TEXT,
    category_id BIGINT REFERENCES interests(id),
    difficulty INT CHECK(difficulty BETWEEN 1 AND 5),
    image_url VARCHAR(255)
);

CREATE TABLE IF NOT EXISTS weekly_program_days (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    challenge_id BIGINT NOT NULL REFERENCES challenges(id),
    day INT NOT NULL,
    title VARCHAR(255),
    description TEXT,
    UNIQUE(challenge_id, day)
);

CREATE TABLE IF NOT EXISTS challenge_materials (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    challenge_id BIGINT NOT NULL REFERENCES challenges(id),
    material_text TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS day_tasks (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    challenge_id BIGINT NOT NULL REFERENCES challenges(id),
    day INT NOT NULL,
    title VARCHAR(255),
    intro TEXT,
    materials_json JSONB,
    steps_json JSONB,
    tips_json JSONB,
    questions_json JSONB,
    gallery_json JSONB,
    UNIQUE(challenge_id, day)
);

CREATE TABLE IF NOT EXISTS user_challenges (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    challenge_id BIGINT NOT NULL REFERENCES challenges(id),
    start_date TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    current_day INT DEFAULT 1,
    total_days INT NOT NULL,
    completed BOOLEAN NOT NULL DEFAULT FALSE
);

CREATE TABLE IF NOT EXISTS day_completions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    challenge_id BIGINT NOT NULL REFERENCES challenges(id),
    day_number INT NOT NULL,
    mood INT,
    note_text TEXT,
    photo_path VARCHAR(500),
    completed_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);